name: Deploy static content to Pages

on:
  pull_request:
    branches: ['main']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: npm run prettier:check

      - name: Build the html files
        run: npm run build
